version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: babel-preset-gatsby
    versions:
    - 0.12.0
    - 1.0.0
    - 1.1.0
    - 1.2.0
    - 1.3.0
  - dependency-name: gatsby-image
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: stylelint-config-standard
    versions:
    - 21.0.0
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.3
  - dependency-name: tailwindcss
    versions:
    - 2.1.1
  - dependency-name: gatsby-plugin-typescript
    versions:
    - 2.12.0
    - 2.12.1
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
