version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          with-cache: true
      - run: yarn global add firebase-tools
      - run: yarn build
      - run: yarn firebase deploy --token "$FIREBASE_TOKEN"

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy
